FROM node:22 AS builder
WORKDIR /app
COPY . .
RUN npm install

# Stage 2: Runtime environment
FROM node:22-slim

WORKDIR /app

# Copy built code and dependencies from builder stage
COPY --from=builder /app/node_modules ./node_modules
COPY . .

EXPOSE 3000
CMD ["npm", "start","--","--host","--port","3000"]
